spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useTimezone=true
    username: root
    password: 123456
  application:
    name: Inventory
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos server 地址
      client:
        service:
          name: inventory-service    # Nacos 注册的应用名
server:
  port: 9200