spring:
  application:
    name: Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos server 地址
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**    #以system开头的请求都负载到system服务
server:
  port: 10052