spring:
  application:
    name: System
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos server 地址
      client:
        service:
          name: system-service    # Nacos 注册的应用名
server:
  port: 1111