spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useTimezone=true
    username: root
    password: 123456
  application:
    name: System
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos server 地址
      client:
        service:
          name: system-service    # Nacos 注册的应用名
server:
  port: 1111